# Generated by Django 5.2 on 2025-04-30 06:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_team_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password_hash', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('team_owner', 'Team Owner'), ('player', 'Player'), ('guest', 'Guest')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='team_name',
        ),
        migrations.RemoveField(
            model_name='team',
            name='description',
        ),
        migrations.RemoveField(
            model_name='team',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='team',
            name='role',
        ),
        migrations.AddField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='team_logo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Match',
        ),
    ]
