# Generated by Django 5.2 on 2025-04-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_team_team_logo_match_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='player_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='role',
            new_name='position',
        ),
        migrations.RemoveField(
            model_name='player',
            name='runs',
        ),
        migrations.RemoveField(
            model_name='player',
            name='wickets',
        ),
        migrations.AddField(
            model_name='player',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.CharField(max_length=100),
        ),
    ]
