# Generated by Django 5.2 on 2025-04-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_player_age_alter_player_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_logo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
