# Generated by Django 5.2 on 2025-05-01 03:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_player_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='winner',
        ),
        migrations.AddField(
            model_name='match',
            name='end_time',
            field=models.TimeField(default=datetime.time(18, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='start_time',
            field=models.TimeField(default=datetime.time(15, 30)),
            preserve_default=False,
        ),
    ]
