# Generated by Django 5.2 on 2025-05-01 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_playerstats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstats',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.player'),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='role',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='runs',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='wickets',
            field=models.IntegerField(),
        ),
    ]
