# Generated by Django 5.2 on 2025-05-01 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_playerstats_player_alter_playerstats_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstats',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playerstats', to='myapp.player'),
        ),
    ]
