# Generated by Django 5.2 on 2025-05-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_match_end_time_remove_match_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='result',
            field=models.CharField(blank=True, default='Not Decided', max_length=100),
        ),
        migrations.AlterModelTable(
            name='match',
            table='matches',
        ),
    ]
