# Generated by Django 5.2 on 2025-05-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_match_start_time_alter_match_match_date_and_more'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='match',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='result',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterModelTable(
            name='match',
            table=None,
        ),
       
    ]
