# Generated by Django 5.2 on 2025-05-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_remove_team_user_remove_match_user_match_end_time_and_more'),
    ]

    operations = [
       
        migrations.AddField(
            model_name='team',
            name='coach_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
       
    ]
